---
  - name: extract files
    become: true
    unarchive:
      src: files/artifact.tar.gz
      dest: /home/ubuntu
  
  - name: start app
    become: true
    shell : |
        cd /home/ubuntu/
        sudo npm install
        sudo pm2 stop default
        sudo pm2 start npm -- start